@baseUrl = http://localhost:8000/api
@bearerToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzUxMTk2NjcyLCJleHAiOjE3NTEyMDAyNzIsIm5iZiI6MTc1MTE5NjY3MiwianRpIjoibUFGQlA4a3lwOWduUzBjUCIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.hYl-Py1Tz8qEJ9sYqFRMe1QmILV9FE6tg5DcaIQFWXo


POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "test@example.com",
    "password": "123"
}


### Base URL and Bearer Token (Reusable Variables)

### Test: Kirim permintaan pertemanan (POST /friend)
POST {{baseUrl}}/friends
Authorization: Bearer {{bearerToken}}
Content-Type: application/json
Accept: application/json

{
  "friend_id": 1    
}

### Test: Lihat daftar teman (GET /friend)
GET {{baseUrl}}/friend
Authorization: Bearer {{bearerToken}}
Accept: application/json


